// Nur die Teile von Three.js, die die Szenen wirklich brauchen. Mit benannten
// Importen kann der Bundler den Rest weglassen; `import('three')` als Ganzes
// lud jedes Mal die komplette Bibliothek.
export {
  AdditiveBlending,
  BufferAttribute,
  BufferGeometry,
  CanvasTexture,
  Color,
  ConeGeometry,
  DoubleSide,
  EdgesGeometry,
  Group,
  IcosahedronGeometry,
  LineBasicMaterial,
  LineSegments,
  Mesh,
  MeshBasicMaterial,
  OctahedronGeometry,
  OrthographicCamera,
  PerspectiveCamera,
  PlaneGeometry,
  Points,
  PointsMaterial,
  RingGeometry,
  Scene,
  ShaderMaterial,
  Sprite,
  SpriteMaterial,
  SRGBColorSpace,
  TetrahedronGeometry,
  TorusGeometry,
  Vector3,
  WebGLRenderer,
} from 'three'
